from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.11.0")

configfile: "config/config.yaml"


##### load rules #####
include: "rules/common.smk"
include: "rules/joint-calling.smk"


##### target rules #####
#input: directory(expand("genotyping/genomicsdb/genmark_chr{chrom}",chrom=chroms)),
rule all:
    input: expand("genotyped/joint-called/{project}_chr{chrom}_genotyped.vcf.gz", project=config['project'],chrom=chrom_list)